In [ ]:

import pandas as pd

file_path = r"D:\Depi\finalproject\planning\sample_-_superstore.xls"
df_source = pd.read_excel(file_path, sheet_name='source', engine='xlrd')
df_returns = pd.read_excel(file_path, sheet_name='Returns', engine='xlrd')
df_people = pd.read_excel(file_path, sheet_name='People', engine='xlrd')

df_final = pd.merge(df_source, df_returns, on='Order ID', how='left')

df_source.columns = df_source.columns.str.strip()
df_returns.columns = df_returns.columns.str.strip()

df_final = pd.merge(df_source, df_returns, on='Order ID', how='left')
df_final.head()

df_final = pd.merge(df_final, df_people, on='Region', how='left')

df_final['Returned'] = df_final['Returned'].fillna('No')


df_final['Returned Flag'] = (df_final['Returned'] == 'Yes').astype(int)



df_final['Order Date'] = pd.to_datetime(df_final['Order Date'])
df_final['Ship Date']  = pd.to_datetime(df_final['Ship Date'])

In [34]:
df_final.shape

(10194, 24)

In [35]:
df_final.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Returned', 'Regional Manager', 'Returned Flag'],
      dtype='object')

In [37]:
df_final.dtypes

Row ID                       int64
Order ID                    object
Order Date          datetime64[ns]
Ship Date           datetime64[ns]
Ship Mode                   object
Customer ID                 object
Customer Name               object
Segment                     object
Country/Region              object
City                        object
State/Province              object
Postal Code                 object
Region                      object
Product ID                  object
Category                    object
Sub-Category                object
Product Name                object
Sales                      float64
Quantity                     int64
Discount                   float64
Profit                     float64
Returned                    object
Regional Manager            object
Returned Flag                int32
dtype: object

In [39]:
df_final.info

<bound method DataFrame.info of        Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800 2023-01-03 2023-01-07  Standard Class
1           2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
2           3  US-2023-112326 2023-01-04 2023-01-08  Standard Class
3           4  US-2023-112326 2023-01-04 2023-01-08  Standard Class
4           5  US-2023-141817 2023-01-05 2023-01-12  Standard Class
...       ...             ...        ...        ...             ...
10189   10190  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10190   10191  US-2026-115427 2026-12-30 2027-01-03  Standard Class
10191   10192  US-2026-156720 2026-12-30 2027-01-03  Standard Class
10192   10193  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10193   10194  CA-2026-143500 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ...         Category Sub-Category  \
0            Houston  ...  Office Supplies        Paper
1         Naperville  ...  Office Supplies      Binders
2         Naperville  ...  Office Supplies       Labels
3         Naperville  ...  Office Supplies      Storage
4       Philadelphia  ...  Office Supplies          Art
...              ...  ...              ...          ...
10189  New York City  ...  Office Supplies      Binders
10190      Fairfield  ...  Office Supplies      Binders
10191       Loveland  ...  Office Supplies    Fasteners
10192  New York City  ...       Technology       Phones
10193  Charlottetown  ...  Office Supplies      Binders

                                            Product Name    Sales Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448        2
1             GBC Standard Plastic Binding Systems Combs    3.540        2
2                                              Avery 508   11.784        3
3                          SAFCO Boltless Steel Shelving  272.736        3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536        3
...                                                  ...      ...      ...
10189               Wilson Jones Legal Size Ring Binders   52.776        3
10190                                 GBC Binding covers   20.720        2
10191                                Bagged Rubber Bands    3.024        3
10192                          Gear Head AU3700S Headset   90.930        7
10193                        Wilson Jones Impact Binders    3.024        3

      Discount   Profit  Returned   Regional Manager  Returned Flag
0          0.2   5.5512        No  Roxanne Rodriguez              0
1          0.8  -5.4870        No  Roxanne Rodriguez              0
2          0.2   4.2717        No  Roxanne Rodriguez              0
3          0.2 -64.7748        No  Roxanne Rodriguez              0
4          0.2   4.8840        No        Chuck Magee              0
...        ...      ...       ...                ...            ...
10189      0.2  19.7910        No        Chuck Magee              0
10190      0.2   6.4750       Yes    Sadie Pawthorne              1
10191      0.2  -0.6048        No    Sadie Pawthorne              0
10192      0.0   2.7279        No        Chuck Magee              0
10193      0.2  -0.6048        No        Chuck Magee              0

[10194 rows x 24 columns]>

In [50]:
df_final.drop(columns=[ 'Returned Flag']).describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002942720,2025-05-03 10:52:45.626839296,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [49]:
df_final.describe(include ='object')

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Returned,Regional Manager
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,5111,4,804,800,3,2,542,59,654,4,1862,3,17,1849,2,4
top,US-2026-100111,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,10035,West,FUR-FU-10004270,Office Supplies,Binders,Staples,No,Sadie Pawthorne
freq,14,6120,41,41,5281,9994,915,2001,263,3253,20,6128,1548,50,9394,3253

In [51]:
df_final.groupby('Category')['Profit'].sum()

Category
Furniture           19729.9956
Office Supplies    126023.4434
Technology         146543.3756
Name: Profit, dtype: float64

In [54]:
df_final.isnull().mean()*100

Row ID              0.0
Order ID            0.0
Order Date          0.0
Ship Date           0.0
Ship Mode           0.0
Customer ID         0.0
Customer Name       0.0
Segment             0.0
Country/Region      0.0
City                0.0
State/Province      0.0
Postal Code         0.0
Region              0.0
Product ID          0.0
Category            0.0
Sub-Category        0.0
Product Name        0.0
Sales               0.0
Quantity            0.0
Discount            0.0
Profit              0.0
Returned            0.0
Regional Manager    0.0
Returned Flag       0.0
dtype: float64

In [57]:
df_final.duplicated().sum()

0